CREATE TABLE IF NOT EXISTS SINGER (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(60) NOT NULL
  , PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MP3 (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(100) NOT NULL
  , SINGER_ID INT NOT NULL
  , PRIMARY KEY (ID)
  , CONSTRAINT FK_MP3 FOREIGN KEY (SINGER_ID)
REFERENCES SINGER (ID)
);

